# Generated by Django 5.2.10 on 2026-02-21 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_project_id'),
        ('home', '0002_project_hourly_rate_timesheet_timesheettask'),
    ]

    operations = [
    ]
