# Generated by Django 6.0.3 on 2026-05-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_project_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='project',
            name='churn_large',
            field=models.PositiveIntegerField(default=600, help_text='Lines ≤ this → 3.0 hrs  (large commit)'),
        ),
        migrations.AddField(
            model_name='project',
            name='churn_medium',
            field=models.PositiveIntegerField(default=300, help_text='Lines ≤ this → 1.5 hrs  (medium commit)'),
        ),
        migrations.AddField(
            model_name='project',
            name='churn_small',
            field=models.PositiveIntegerField(default=100, help_text='Lines ≤ this → 0.75 hrs (small commit)'),
        ),
        migrations.AddField(
            model_name='project',
            name='churn_tiny',
            field=models.PositiveIntegerField(default=30, help_text='Lines ≤ this → 0.25 hrs (tiny commit)'),
        ),
        migrations.AddField(
            model_name='project',
            name='github_repo',
            field=models.CharField(blank=True, help_text='GitHub repo in "owner/repo" format, e.g. myorg/myrepo', max_length=200),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='github_pr_number',
            field=models.PositiveIntegerField(blank=True, help_text='PR number (for PR entries)', null=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='github_sha',
            field=models.CharField(blank=True, help_text='Commit SHA (for commit entries)', max_length=40),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='hours_overridden',
            field=models.BooleanField(default=False, help_text='Admin manually adjusted auto hours'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('GITHUB_COMMIT', 'GitHub Commit'), ('GITHUB_PR', 'GitHub PR Merge')], default='MANUAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='mode',
            field=models.CharField(choices=[('DEV', 'Development'), ('PROD', 'Production'), ('MAINT', 'Maintenance')], default='DEV', max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='total_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='timesheettask',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='timesheettask',
            name='hours',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
