# Generated by Django 6.0.3 on 2026-07-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_project_options_project_churn_large_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deploy_command',
            field=models.CharField(blank=True, help_text='Shell command to run on the VPS to deploy this project. e.g. "cd /opt/Qpet && ./deploy_qpet.sh". Leave blank to hide the Deploy button.', max_length=500),
        ),
    ]
