# Generated by Django 6.0.3 on 2026-07-18 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_project_deploy_command'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeployScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Short name, e.g. "Full deploy (web+admin)" or "Frontend only"', max_length=100)),
                ('command', models.CharField(help_text='Shell command to run, e.g. "bash /opt/Qpet/deploy_simple.sh"', max_length=500)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deploy_scripts', to='home.project')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='active_deploy_script',
            field=models.ForeignKey(blank=True, help_text='Pick which deploy script runs when the Deploy button is clicked.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.deployscript'),
        ),
    ]
