# Generated by Django 6.0.1 on 2026-07-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_deployscript_project_active_deploy_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='test_deploy_command',
            field=models.CharField(blank=True, help_text='Shell command to run on the VPS to deploy to the TEST server. e.g. "cd /opt/Qpet-test && ./deploy_qpet_test.sh". Leave blank to hide the Test Deploy button.', max_length=500),
        ),
    ]
