# Generated by Django 6.0.1 on 2026-07-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_project_test_deploy_command'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='churn_small',
            field=models.PositiveIntegerField(default=100, help_text='Lines ≤ this → 0.25 hrs (15 mins) (small commit)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='churn_tiny',
            field=models.PositiveIntegerField(default=30, help_text='Lines ≤ this → 0.17 hrs (10 mins) (tiny commit)'),
        ),
    ]
