# Generated by Django 6.0.1 on 2026-07-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_project_churn_small_alter_project_churn_tiny'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheettask',
            name='github_sha',
            field=models.CharField(blank=True, help_text='Commit SHA', max_length=40),
        ),
    ]
