# Generated by Django 6.0.1 on 2026-07-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_bankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='branch',
            field=models.CharField(blank=True, max_length=150, verbose_name='Branch Name'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='swift_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='SWIFT Code'),
        ),
    ]
