# Generated by Django 6.0.1 on 2026-07-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminlogin',
            name='username',
        ),
        migrations.AddField(
            model_name='adminlogin',
            name='email',
            field=models.EmailField(default='jibin@tresvance.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='adminlogin',
            name='name',
            field=models.CharField(default='Jibin Jose', max_length=150),
        ),
    ]
