# Generated by Django 6.0.1 on 2026-07-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_adminlogin_username_adminlogin_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='activity_log',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='task',
            name='actual_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='task',
            name='attachments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='task',
            name='comments',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
