# Generated by Django 6.0.1 on 2026-07-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_task_activity_log_task_actual_hours_task_attachments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployscript',
            name='interactive',
            field=models.BooleanField(default=False, help_text='Check if this script is interactive and requires parameters (branch, services, migrations) to be asked before executing.'),
        ),
        migrations.AddField(
            model_name='project',
            name='test_deploy_interactive',
            field=models.BooleanField(default=False, help_text='Check if the test deploy command is interactive and requires parameters (branch, services, migrations) to be asked.'),
        ),
    ]
