# Generated by Django 6.0.3 on 2026-08-11 05:42

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_task_activity_log_task_actual_hours_task_attachments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Summary title of the change request', max_length=250)),
                ('client_name', models.CharField(help_text='Client Organization / Company Name', max_length=150)),
                ('client_email', models.EmailField(blank=True, help_text='Client contact email', max_length=254)),
                ('requested_by_contact', models.CharField(blank=True, help_text='Client contact person name', max_length=150)),
                ('request_date', models.DateField(default=datetime.date.today, help_text='Date request was submitted by client')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Shared with Client', 'Shared with Client'), ('Client Approved', 'Client Approved'), ('In Development', 'In Development'), ('Completed', 'Completed'), ('Rejected', 'Rejected')], default='Draft', max_length=30)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20)),
                ('assigned_developer', models.CharField(blank=True, help_text='Developer or team member assigned', max_length=150)),
                ('description', models.TextField(help_text='Detailed description of changes requested by the client')),
                ('technical_scope', models.TextField(blank=True, help_text='Developer technical implementation scope and notes')),
                ('estimated_hours', models.DecimalField(decimal_places=2, default=0, help_text='Estimated development effort in hours', max_digits=6)),
                ('target_completion_date', models.DateField(blank=True, help_text='Target completion date for development', null=True)),
                ('client_approved_by', models.CharField(blank=True, help_text='Name of person approving from client side', max_length=150)),
                ('client_approval_date', models.DateField(blank=True, help_text='Date approved by client', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='home.project')),
            ],
            options={
                'verbose_name': 'Change Request',
                'verbose_name_plural': 'Change Requests',
                'ordering': ['-request_date', '-created_at'],
            },
        ),
    ]
