# Generated by Django 6.0.1 on 2026-09-25 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_changerequest'),
        ('home', '0017_deployscript_interactive_and_more'),
    ]

    operations = [
    ]
