# Generated by Django 6.0.1 on 2026-09-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_merge_20260925_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='links',
            field=models.JSONField(blank=True, default=list, help_text="Multiple links such as Test Server, Development Link, Production, etc. Format: [{'title': '...', 'url': '...', 'env': 'test'}]"),
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='title',
            field=models.CharField(blank=True, help_text='Optional summary title', max_length=250),
        ),
    ]
