# Generated by Django 6.0.1 on 2026-09-25 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_project_links_alter_changerequest_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('env', models.CharField(choices=[('prod', '🟢 Production (Live)'), ('test', '🟠 Test Server'), ('dev', '🔵 Development'), ('staging', '🟣 Staging'), ('other', '⚪ Other / Custom')], default='test', help_text='Environment type for badge styling (e.g. Test, Dev, Production)', max_length=20, verbose_name='Environment')),
                ('title', models.CharField(help_text='Display name, e.g. "Live / Production", "Test Server", "Development"', max_length=150)),
                ('url', models.URLField(help_text='Target URL, e.g. https://test.bmce.ac.in/', max_length=500)),
                ('remarks', models.CharField(blank=True, help_text='Remarks / notes for this link, e.g. "QA testing build v2.4", "Local port 3000"', max_length=300, verbose_name='Remarks / Notes')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_links', to='home.project')),
            ],
            options={
                'verbose_name': 'Project Environment Link',
                'verbose_name_plural': 'Project Environments & Links',
                'ordering': ['id'],
            },
        ),
    ]
