# Generated by Django 6.0.1 on 2026-09-25 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_projectlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(help_text='e.g. AWS EC2 t3.large, DigitalOcean Droplet, Vercel Pro, Namecheap .com domain', max_length=150, verbose_name='Service / Item Name')),
                ('provider', models.CharField(help_text='e.g. AWS, DigitalOcean, Hostinger, Vercel, Namecheap, Cloudflare, OpenAI, Twilio', max_length=100, verbose_name='Platform / Provider')),
                ('category', models.CharField(choices=[('HOSTING', '☁️ Hosting & Cloud Server'), ('DOMAIN', '🌐 Domain Registration / Renewal'), ('DATABASE', '🗄️ Database & Storage'), ('EMAIL_SMS', '✉️ Email, SMS & WhatsApp API'), ('SSL_SECURITY', '🔒 SSL, WAF & Security'), ('SOFTWARE_LICENSE', '💻 Software & Tool License'), ('API_AI', '🤖 API & AI Model Usage'), ('MAINTENANCE', '🛠️ Maintenance & Infrastructure'), ('OTHER', '📦 Other Platform Expense')], default='HOSTING', max_length=40, verbose_name='Category')),
                ('billing_cycle', models.CharField(choices=[('MONTHLY', 'Monthly (Recurring)'), ('YEARLY', 'Yearly / Annual (Recurring)'), ('QUARTERLY', 'Quarterly (Every 3 months)'), ('SEMI_ANNUAL', 'Semi-Annual (Every 6 months)'), ('ONE_TIME', 'One-Time (Fixed Expense)')], default='MONTHLY', max_length=30, verbose_name='Billing Cycle')),
                ('cost_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount paid to vendor/platform (what company pays)', max_digits=12, verbose_name='Vendor Cost (Expense)')),
                ('client_charge_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount billed to client. If included in retainer or unbilled, leave 0', max_digits=12, verbose_name='Client Billed Amount')),
                ('currency', models.CharField(choices=[('INR', '₹ INR'), ('USD', '$ USD'), ('EUR', '€ EUR'), ('GBP', '£ GBP'), ('AED', 'AED')], default='INR', max_length=10, verbose_name='Currency')),
                ('billing_date', models.DateField(help_text='Date invoice was generated or period started', verbose_name='Billing / Invoice Date')),
                ('due_date', models.DateField(blank=True, help_text='Expiration or next scheduled renewal date', null=True, verbose_name='Due / Renewal Date')),
                ('status', models.CharField(choices=[('PAID', '✅ Paid'), ('PENDING', '⏳ Payment Pending'), ('OVERDUE', '⚠️ Overdue'), ('RENEWED', '🔄 Renewed'), ('CANCELLED', '❌ Cancelled / Expired')], default='PAID', max_length=20, verbose_name='Payment Status')),
                ('paid_by', models.CharField(blank=True, help_text='e.g. Company Card, Client Card, Bank Transfer, PayPal, Joel', max_length=100, verbose_name='Paid By / Method')),
                ('invoice_ref', models.CharField(blank=True, help_text='Vendor invoice or transaction reference ID', max_length=100, verbose_name='Invoice # / Reference')),
                ('invoice_url', models.URLField(blank=True, help_text='Direct link to invoice PDF, receipt, or portal bill', max_length=500, verbose_name='Invoice URL / Receipt Link')),
                ('remarks', models.TextField(blank=True, help_text='Server IP, specifications, renewal details, or client billing terms', verbose_name='Remarks / Server Specs / Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, help_text='Project associated with this hosting/platform bill (or leave blank if company-wide)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_bills', to='home.project', verbose_name='Associated Project')),
            ],
            options={
                'verbose_name': 'Client Bill / Platform Expense',
                'verbose_name_plural': 'Client Bills & Platform Expenses',
                'ordering': ['-due_date', '-billing_date', '-id'],
            },
        ),
    ]
