# Generated by Django 6.0.1 on 2026-09-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_clientbill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientbill',
            name='category',
            field=models.CharField(choices=[('HOSTING', 'Hosting & Cloud Server'), ('DOMAIN', 'Domain Registration / Renewal'), ('DATABASE', 'Database & Storage'), ('EMAIL_SMS', 'Email, SMS & WhatsApp API'), ('SSL_SECURITY', 'SSL, WAF & Security'), ('SOFTWARE_LICENSE', 'Software & Tool License'), ('API_AI', 'API & AI Model Usage'), ('MAINTENANCE', 'Maintenance & Infrastructure'), ('OTHER', 'Other Platform Expense')], default='HOSTING', max_length=40, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='clientbill',
            name='currency',
            field=models.CharField(choices=[('INR', 'INR (₹)'), ('USD', 'USD ($)'), ('EUR', 'EUR (€)'), ('GBP', 'GBP (£)'), ('AED', 'AED')], default='INR', max_length=10, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='clientbill',
            name='status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Payment Pending'), ('OVERDUE', 'Overdue'), ('RENEWED', 'Renewed'), ('CANCELLED', 'Cancelled / Expired')], default='PAID', max_length=20, verbose_name='Payment Status'),
        ),
    ]
