# Generated by Django 6.0.1 on 2026-09-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_clientbill_category_alter_clientbill_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectlink',
            name='env',
            field=models.CharField(choices=[('prod', 'Production (Live)'), ('test', 'Test Server'), ('dev', 'Development'), ('staging', 'Staging'), ('other', 'Other / Custom')], default='test', help_text='Environment type for badge styling (e.g. Test, Dev, Production)', max_length=20, verbose_name='Environment'),
        ),
    ]
