# Generated by Django 6.0.1 on 2026-09-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_projectlink_env'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_visible_in_list',
            field=models.BooleanField(default=True, help_text='Show this project on the frontend project list page.', verbose_name='Visible in Project List'),
        ),
    ]
